/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\assets\models\island.glb 
Author: Pixman (https://sketchfab.com/Pixmani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-medieval-family-house-d99dcaed249845fa96cb04693304191a
Title: Stylized medieval family house
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/island.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.polySurface18439_listva_6_0.geometry} material={materials.listva_6} />
        <mesh geometry={nodes.polySurface18439_listva_6_0_1.geometry} material={materials.listva_6} />
        <mesh geometry={nodes.polySurface18439_metal_1_0.geometry} material={materials.metal_1} />
        <mesh geometry={nodes.polySurface18439_krysha_2_2_0.geometry} material={materials.krysha_2_2} />
        <mesh geometry={nodes.polySurface18439_flow_9_0.geometry} material={materials.flow_9} />
        <mesh geometry={nodes.polySurface18439_flow_2_0.geometry} material={materials.flow_2} />
        <mesh geometry={nodes.polySurface18439_derevo_6_0.geometry} material={materials.derevo_6} />
        <mesh geometry={nodes.polySurface18439_listva_3_0.geometry} material={materials.listva_3} />
        <mesh geometry={nodes.polySurface18439_metal_2_0.geometry} material={materials.metal_2} />
        <mesh geometry={nodes.polySurface18439_krysha_2_1_0.geometry} material={materials.krysha_2_1} />
        <mesh geometry={nodes.polySurface18439_zelty_0.geometry} material={materials.zelty} />
        <mesh geometry={nodes.polySurface18439_odezda_7_0.geometry} material={materials.odezda_7} />
        <mesh geometry={nodes.polySurface18439_krysha_2_3_0.geometry} material={materials.krysha_2_3} />
        <mesh geometry={nodes.polySurface18439_derevo_4_0.geometry} material={materials.derevo_4} />
        <mesh geometry={nodes.polySurface18439_seno_0.geometry} material={materials.seno} />
        <mesh geometry={nodes.polySurface18439_derevo_3_0.geometry} material={materials.derevo_3} />
        <mesh geometry={nodes.polySurface18439_derevo_7_0.geometry} material={materials.derevo_7} />
        <mesh geometry={nodes.polySurface18439_verevka_0.geometry} material={materials.verevka} />
        <mesh geometry={nodes.polySurface18439_derevo_1_0.geometry} material={materials.derevo_1} />
        <mesh geometry={nodes.polySurface18439_listva_7_0.geometry} material={materials.listva_7} />
        <mesh geometry={nodes.polySurface18439_listva_4_0.geometry} material={materials.listva_4} />
        <mesh geometry={nodes.polySurface18439_krysha_2_4_0.geometry} material={materials.krysha_2_4} />
        <mesh geometry={nodes.polySurface18439_listva_2_0.geometry} material={materials.listva_2} />
        <mesh geometry={nodes.polySurface18439_derevo_2_0.geometry} material={materials.derevo_2} />
        <mesh geometry={nodes.polySurface18439_derevo_5_0.geometry} material={materials.derevo_5} />
        <mesh geometry={nodes.polySurface18439_kamen_7_0.geometry} material={materials.kamen_7} />
        <mesh geometry={nodes.polySurface18439_jajco_0.geometry} material={materials.jajco} />
        <mesh geometry={nodes.polySurface18439_podushka_0.geometry} material={materials.podushka} />
        <mesh geometry={nodes.polySurface18439_metal_3_0.geometry} material={materials.metal_3} />
        <mesh geometry={nodes.polySurface18439_listva_8_0.geometry} material={materials.listva_8} />
        <mesh geometry={nodes.polySurface18439_flow_5_0.geometry} material={materials.flow_5} />
        <mesh geometry={nodes.polySurface18439_okno_2_0.geometry} material={materials.okno_2} />
        <mesh geometry={nodes.polySurface18439_glaz_0.geometry} material={materials.glaz} />
        <mesh geometry={nodes.polySurface18439_listva_5_0.geometry} material={materials.listva_5} />
        <mesh geometry={nodes.polySurface18439_lampa_0.geometry} material={materials.lampa} />
        <mesh geometry={nodes.polySurface18439_odezda_5_0.geometry} material={materials.odezda_5} />
        <mesh geometry={nodes.polySurface18439_odezda_1_0.geometry} material={materials.odezda_1} />
        <mesh geometry={nodes.polySurface18439_odezda_6_0.geometry} material={materials.odezda_6} />
        <mesh geometry={nodes.polySurface18439_repa_2_0.geometry} material={materials.repa_2} />
        <mesh geometry={nodes.polySurface18439_krasny_0.geometry} material={materials.krasny} />
        <mesh geometry={nodes.polySurface18439_kamen_6_0.geometry} material={materials.kamen_6} />
        <mesh geometry={nodes.polySurface18439_kamen_5_0.geometry} material={materials.kamen_5} />
        <mesh geometry={nodes.polySurface18439_igrushka_2_0.geometry} material={materials.igrushka_2} />
        <mesh geometry={nodes.polySurface18439_igrushka_1_0.geometry} material={materials.igrushka_1} />
        <mesh geometry={nodes.polySurface18439_kamen_4_0.geometry} material={materials.kamen_4} />
        <mesh geometry={nodes.polySurface18439_siny_0.geometry} material={materials.siny} />
        <mesh geometry={nodes.polySurface18439_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface18439_repa_1_0.geometry} material={materials.repa_1} />
        <mesh geometry={nodes.polySurface18439_kamen_2_0.geometry} material={materials.kamen_2} />
        <mesh geometry={nodes.polySurface18439_matras_0.geometry} material={materials.matras} />
        <mesh geometry={nodes.polySurface18439_repa_3_0.geometry} material={materials.repa_3} />
        <mesh geometry={nodes.polySurface18439_zeleny_0.geometry} material={materials.zeleny} />
        <mesh geometry={nodes.polySurface18439_trava_2_0.geometry} material={materials.trava_2} />
        <mesh geometry={nodes.polySurface18439_zemla_3_0.geometry} material={materials.zemla_3} />
        <mesh geometry={nodes.polySurface18439_zemla_2_0.geometry} material={materials.zemla_2} />
        <mesh geometry={nodes.polySurface18439_black_0.geometry} material={materials.black} />
        <mesh geometry={nodes.polySurface18439_kamen_3_0.geometry} material={materials.kamen_3} />
        <mesh geometry={nodes.polySurface18439_dom_stena_2_0.geometry} material={materials.dom_stena_2} />
        <mesh geometry={nodes.polySurface18439_gradka_0.geometry} material={materials.gradka} />
        <mesh geometry={nodes.polySurface18439_bumaga_0.geometry} material={materials.bumaga} />
        <mesh geometry={nodes.polySurface18439_golova_0.geometry} material={materials.golova} />
        <mesh geometry={nodes.polySurface18439_derevo_8_0.geometry} material={materials.derevo_8} />
        <mesh geometry={nodes.polySurface18439_listva_1_0.geometry} material={materials.listva_1} />
        <mesh geometry={nodes.polySurface18439_odezda_8_0.geometry} material={materials.odezda_8} />
        <mesh geometry={nodes.polySurface18439_derevo_stvol_0.geometry} material={materials.derevo_stvol} />
        <mesh geometry={nodes.polySurface18439_odezda_2_0.geometry} material={materials.odezda_2} />
        <mesh geometry={nodes.polySurface18439_odezda_3_0.geometry} material={materials.odezda_3} />
        <mesh geometry={nodes.polySurface18439_odezda_4_0.geometry} material={materials.odezda_4} />
        <mesh geometry={nodes.polySurface18439_kamen_1_0.geometry} material={materials.kamen_1} />
        <mesh geometry={nodes.polySurface18439_mylo_0.geometry} material={materials.mylo} />
        <mesh geometry={nodes.polySurface18439_shlapa_0.geometry} material={materials.shlapa} />
      </group>
    </group>
  )
}

useGLTF.preload('/island.glb')
