/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\assets\models\blackKid.glb 
Author: anonfunction (https://sketchfab.com/anonfunction)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modz-kid-1-cdef991485914486bbc11bb1a06aaa07
Title: Modz Kid #1
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function BlackKid(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("./assets/models/blackKid.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    const action = actions[names[0]];
    action?.reset()?.fadeIn(0.5)?.play();
    return () => action.fadeOut(0.5);
  }, [actions, names]);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={0.6}
      position={[0, -1.05, 4]}
      rotation-y={Math.PI / 2}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Mixamo_rig_184">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="23_JERSEY_178" />
                  <group name="23_SHORTS_179" />
                  <group name="ANIME_HAIR_180" />
                  <group name="DARK_181" />
                  <group name="FORCE_23_182" />
                  <group name="MODZ_CHAIN_BY_CJ_GOLD_183" />
                  <group name="SUNGLASSES_GREEN_177_correction">
                    <group name="SUNGLASSES_GREEN_177" />
                  </group>
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials["23_J"]}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.SHORTS_23_JERSEY_Baked}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials.ANIME_HAIR}
                    skeleton={nodes.Object_11.skeleton}
                  />
                  <skinnedMesh
                    name="Object_13"
                    geometry={nodes.Object_13.geometry}
                    material={materials.DARK}
                    skeleton={nodes.Object_13.skeleton}
                  />
                  <skinnedMesh
                    name="Object_14"
                    geometry={nodes.Object_14.geometry}
                    material={materials.Eyelashes}
                    skeleton={nodes.Object_14.skeleton}
                  />
                  <skinnedMesh
                    name="Object_15"
                    geometry={nodes.Object_15.geometry}
                    material={materials.Eye_moisture}
                    skeleton={nodes.Object_15.skeleton}
                  />
                  <skinnedMesh
                    name="Object_17"
                    geometry={nodes.Object_17.geometry}
                    material={materials["Air_Jordan_-_Floor"]}
                    skeleton={nodes.Object_17.skeleton}
                  />
                  <skinnedMesh
                    name="Object_18"
                    geometry={nodes.Object_18.geometry}
                    material={materials["Air_Jordan_-_Black"]}
                    skeleton={nodes.Object_18.skeleton}
                  />
                  <skinnedMesh
                    name="Object_19"
                    geometry={nodes.Object_19.geometry}
                    material={materials["Air_Jordan_-_White"]}
                    skeleton={nodes.Object_19.skeleton}
                  />
                  <skinnedMesh
                    name="Object_20"
                    geometry={nodes.Object_20.geometry}
                    material={materials["Air_Jordan_-_Red"]}
                    skeleton={nodes.Object_20.skeleton}
                  />
                  <skinnedMesh
                    name="Object_21"
                    geometry={nodes.Object_21.geometry}
                    material={materials["Air_Jordan_-_Lace_red"]}
                    skeleton={nodes.Object_21.skeleton}
                  />
                  <skinnedMesh
                    name="Object_23"
                    geometry={nodes.Object_23.geometry}
                    material={materials.MODZ_CHAIN_BY_CJ_GOLD_Baked}
                    skeleton={nodes.Object_23.skeleton}
                  />
                  <skinnedMesh
                    name="Object_201"
                    geometry={nodes.Object_201.geometry}
                    material={materials.SUNGLASSES_GREEN}
                    skeleton={nodes.Object_201.skeleton}
                  />
                  <skinnedMesh
                    name="Object_202"
                    geometry={nodes.Object_202.geometry}
                    material={materials.SUNGLASSES_GREEN_GLASS}
                    skeleton={nodes.Object_202.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./assets/models/blackKid.glb");
