/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\public\assets\models\disabled.glb 
*/

import { useGLTF } from "@react-three/drei";

export default function Disabled(props) {
  const { nodes } = useGLTF("./assets/models/disabled.glb");
  return (
    <group {...props} dispose={null} castShadow>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  );
}

useGLTF.preload("./assets/models/disabled.glb");
