/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\public\assets\models\essence_of_nature.glb 
Author: DailyArt (https://sketchfab.com/D.art)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/essence-of-nature-dcdbf2a99bb94adabeba0913d6dd5012
Title: Essence of nature
*/

import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useLayoutEffect, useRef } from "react";
import { gsap } from "gsap";
import PropTypes from "prop-types";

HeroNature.propTypes = { isMobile: PropTypes.bool.isRequired };
export default function HeroNature({ isMobile, ...props }) {
  const { nodes, materials } = useGLTF("./assets/models/essence_of_nature.glb");
  const tl = useRef();
  const group = useRef();
  const scroll = useScroll();
  useFrame(() => {
    tl.current.seek(scroll?.offset * tl.current.duration());
  });
  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    // First two animations simultaneous
    tl.current.to(group.current.position, {
      x: 0,
      y: 4,
      z: 0,
      duration: 4,
      delay: 4,
    });
  });
  return (
    <group
      {...props}
      ref={group}
      dispose={null}
      scale={isMobile ? 0.03 : 0.07}
      position={[0, isMobile ? -1 : -2, 0]}
    >
      <mesh
        receiveShadow
        geometry={nodes.Retopo_polySurface203_yezi_0.geometry}
        material={materials.yezi}
      />
      <mesh
        receiveShadow
        geometry={nodes.Retopo_polySurface266_yezi_0.geometry}
        material={materials.yezi}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface676_yezi_0.geometry}
        material={materials.yezi}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface677_yezi_0.geometry}
        material={materials.yezi}
      />
      <mesh
        receiveShadow
        geometry={nodes.Retopo_polySurface197_yezi_0.geometry}
        material={materials.yezi}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface509_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface396_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface413_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface468_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface481_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface384_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface550_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface304_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface436_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface437_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.dimo_fuzhi_polySurface589_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface417_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface923_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface484_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.dimo_fuzhi_polySurface501_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface308_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.dimo_fuzhi_polySurface577_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface924_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface925_shui_0.geometry}
        material={materials.shui}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface926_zhuti_0.geometry}
        material={materials.zhuti}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface7_shitou_0.geometry}
        material={materials.shitou}
        position={[0, -0.101, -0.047]}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface193_shitou_0.geometry}
        material={materials.shitou}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface9_shitou_0.geometry}
        material={materials.shitou}
        position={[0.055, 0, -0.12]}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface8_shitou_0.geometry}
        material={materials.shitou}
        position={[0, 0, -0.088]}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface214_shitou_0.geometry}
        material={materials.shitou}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface222_shitou_0.geometry}
        material={materials.shitou}
      />
      <mesh
        receiveShadow
        geometry={nodes.shitou8_polySurface1_shitou_0.geometry}
        material={materials.shitou}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface278_shitou_0.geometry}
        material={materials.shitou}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface262_shitou_0.geometry}
        material={materials.shitou}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface280_shitou_0.geometry}
        material={materials.shitou}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface678_shitou_0.geometry}
        material={materials.shitou}
        position={[0, 0, 0.127]}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface679_shitou_0.geometry}
        material={materials.shitou}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface680_shitou_0.geometry}
        material={materials.shitou}
        position={[0.166, 0, -0.025]}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface683_shitou_0.geometry}
        material={materials.shitou}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface681_shitou_0.geometry}
        material={materials.shitou}
        position={[0.103, 0, 0]}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface917_shitou_0.geometry}
        material={materials.shitou}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface875_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface715_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface756_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface796_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface821_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface741_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface711_zhiwu1_0.geometry}
        material={materials.zhiwu1}
        position={[0, 0.301, 0]}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface810_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface815_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface801_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface805_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface855_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface717_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface877_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface882_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface920_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface892_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface919_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface802_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface809_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface752_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface891_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface893_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface894_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
      <mesh
        receiveShadow
        geometry={nodes.polySurface823_zhiwu1_0.geometry}
        material={materials.zhiwu1}
      />
    </group>
  );
}

useGLTF.preload("./assets/models/essence_of_nature.glb");
