/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\assets\models\teachers_life.glb 
Author: markus.blend (https://sketchfab.com/markus.blend)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/teachers-life-e3d88392242744a6b701906a2249726e
Title: Teacher's Life
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations, Text, Environment } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { BlackKid } from "./BlackKid";

export default function TeachersLife(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("./assets/models/teachers_life.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions, names } = useAnimations(animations, group);
  useEffect(() => {
    const action = actions?.[names[0]];
    action?.reset()?.fadeIn(0.5).play();
    return () => action?.fadeOut(0.5);
  }, [actions, names]);

  return (
    <>
      <Text
        color="#77BD6B"
        fontSize={0.3}
        position={[2.7, 1, 3]}
        rotation-y={-Math.PI / 1.5}
      >
        Education
      </Text>
      <Text
        color="black"
        fontSize={0.1}
        position={[2.7, 0.5, 3]}
        rotation-y={-Math.PI / 1.5}
      >
        Education, a key human right in the SDGs, goes beyond job preparation to
        foster personal growth,
      </Text>
      <Text
        color="black"
        fontSize={0.1}
        position={[2.7, 0.3, 3]}
        rotation-y={-Math.PI / 1.5}
      >
        participation, and self-determination. In Tunisia, public schools
        struggle with high dropout rates
      </Text>
      <Text
        color="black"
        fontSize={0.1}
        position={[2.7, 0.1, 3]}
        rotation-y={-Math.PI / 1.5}
      >
        (2.8% primary, 26.8% secondary) and declining quality, while
        universities face criticism for misaligned job
      </Text>
      <Text
        color="black"
        fontSize={0.1}
        position={[2.7, -0.1, 3]}
        rotation-y={-Math.PI / 1.5}
      >
        market outcomes. Youth face limited opportunities, leading to despair,
        emigration, and brain drain.
      </Text>
      <Text
        color="black"
        fontSize={0.1}
        position={[2.7, -0.3, 3]}
        rotation-y={-Math.PI / 1.5}
      >
        Existing policies are fragmented, with little youth involvement. A
        unified, inclusive youth policy, rooted in
      </Text>
      <Text
        color="black"
        fontSize={0.1}
        position={[2.7, -0.5, 3]}
        rotation-y={-Math.PI / 1.5}
      >
        human rights and supported by reliable data, is crucial for addressing
        these challenges.
      </Text>
      <BlackKid />
      <Environment
        files="./assets/images/meadow_2_4k.hdr"
        background
        ground={{ scale: 5000, height: 15, radius: 27 }}
      />
      <group
        ref={group}
        {...props}
        dispose={null}
        scale={0.9}
        position={[0, -1, 0.5]}
        rotation-y={-Math.PI / 6}
      >
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="root">
              <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <group
                  name="Chair_4"
                  position={[-0.784, 0, -0.94]}
                  rotation={[-0.437, 0.913, 0.354]}
                >
                  <mesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials["ShadingAtlas.texture"]}
                  />
                  <mesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials.Metal}
                  />
                </group>
                <group
                  name="CoffeeCup_9"
                  position={[-0.458, 1.081, -0.174]}
                  rotation={[-3.101, -1.038, -3.115]}
                  scale={1.5}
                >
                  <mesh
                    name="Object_22"
                    geometry={nodes.Object_22.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group
                  name="rig_Teacher_33"
                  position={[-0.5, -0.061, -0.7]}
                  rotation={[0, Math.PI / 4, 0]}
                >
                  <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <group
                      name="Teacher_32_correction"
                      position={[-0.141, 0.061, 0.849]}
                      rotation={[0, -Math.PI / 4, 0]}
                    >
                      <group name="Teacher_32" />
                    </group>
                    <skinnedMesh
                      name="Object_52"
                      geometry={nodes.Object_52.geometry}
                      material={materials["ShadingAtlas.texture"]}
                      skeleton={nodes.Object_52.skeleton}
                    />
                  </group>
                </group>
                <group
                  name="Timmy'sNotebook_36"
                  position={[-0.268, 1.424, -0.571]}
                  rotation={[1.749, -0.253, -0.982]}
                >
                  <mesh
                    name="Object_58"
                    geometry={nodes.Object_58.geometry}
                    material={materials["notebook.blue"]}
                  />
                  <mesh
                    name="Object_59"
                    geometry={nodes.Object_59.geometry}
                    material={materials.Material}
                  />
                  <mesh
                    name="Object_60"
                    geometry={nodes.Object_60.geometry}
                    material={materials.Drawings}
                  />
                </group>
                <group
                  name="Table_0"
                  position={[-0.1, 0, 0.2]}
                  scale={[1, 0.5, 0.5]}
                >
                  <mesh
                    name="Object_4"
                    geometry={nodes.Object_4.geometry}
                    material={materials["ShadingAtlas.texture"]}
                  />
                </group>
                <group name="ShaderTarget_3" />
                <group name="Room_5" position={[1, 0.6, 0.8]}>
                  <mesh
                    name="Object_12"
                    geometry={nodes.Object_12.geometry}
                    material={materials.Material}
                  />
                  <mesh
                    name="Object_13"
                    geometry={nodes.Object_13.geometry}
                    material={materials.Window}
                  />
                  <mesh
                    name="Object_14"
                    geometry={nodes.Object_14.geometry}
                    material={materials["ShadingAtlas.texture"]}
                  />
                </group>

                <group
                  name="Chalkboard_10"
                  position={[0.528, 1.7, -2.138]}
                  scale={[1.7, 0.9, 0.05]}
                >
                  <mesh
                    name="Object_24"
                    geometry={nodes.Object_24.geometry}
                    material={materials["ShadingAtlas.texture"]}
                  />
                </group>
                <group
                  name="Chalkboard_Drawings_35"
                  position={[0.528, 1.7, -2.133]}
                  scale={[1.7, 0.9, 0.05]}
                >
                  <mesh
                    name="Object_56"
                    geometry={nodes.Object_56.geometry}
                    material={materials.Drawings}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("./assets/models/teachers_life.glb");
